import Head from "next/head";

import productItemListsData from "../data/shopitem.json";

import { Header } from "../components/header/Header.js";
import { Canvas } from "../components/homepage/canvas/Canvas.js";
import { Contactus } from "../components/homepage/Contactus";
import { Testpage } from "../components/Testpage";
import { News } from "../components/homepage/News";
import { Brands } from "../components/homepage/Brands";
import { Footer } from "../components/footer/Footer";

export async function getStaticProps(context) {
  return {
    props: { productItemLists: productItemListsData },
  };
}

export default function Home(props) {
  console.log("dhf", props);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Testpage />
      <Header />
      <Canvas />
      <Contactus />
      <News />
      <Brands />
      <Footer />
    </div>
  );
}
