import Head from "next/head";

// import { Headerone } from "../components/Headerone";
// import { Headertwo } from "../components/Headertwo";
// import { Headerthree } from "../components/Headerthree";
import { Header } from "../components/header/Header.js";
import { Canvas } from "../components/homepage/canvas/Canvastop";

import { Canvasmid } from "../components/homepage/canvas/Canvasmid";
import { Canvaslow } from "../components/homepage/canvas/Canvaslow";
import { Canvasbottomone } from "../components/homepage/canvas/Canvasbottomone";
import { Canvasbottomtwo } from "../components/homepage/canvas/Canvasbottomtwo";
import { Contactus } from "../components/homepage/Contactus";
import { Testpage } from "../components/Testpage";
import { News } from "../components/homepage/News";
import { Brands } from "../components/homepage/Brands";
import { Footer } from "../components/footer/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Testpage />
      {/* <Headerone />
      <Headertwo />
      <Headerthree /> */}
      <Header />
      <Canvas />
      {/* <Canvasmid />
      <Canvaslow />
      <Canvasbottomone />
      <Canvasbottomtwo /> */}
      <Contactus />
      <News />
      <Brands />
      <Footer />
      {/* <News /> */}
      {/*  */}
    </div>
  );
}
