import Head from "next/head";

// import { Headerone } from "../components/Headerone";
// import { Headertwo } from "../components/Headertwo";
// import { Headerthree } from "../components/Headerthree";
import { Header } from "../components/header/Header.js";
import { Canvas } from "../components/homepage/canvas/Canvas.js";

import { Contactus } from "../components/homepage/Contactus";
import { Testpage } from "../components/Testpage";
import { News } from "../components/homepage/News";
import { Brands } from "../components/homepage/Brands";
import { Footer } from "../components/footer/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Testpage />
      <Header />
      <Canvas />
      <Contactus />
      <News />
      <Brands />
      <Footer />
    </div>
  );
}
