import Head from "next/head";

import { Header } from "../components/Header";
import { Canvas } from "../components/Canvas";

import { Canvasmid } from "../components/Canvasmid";
import { Canvaslow } from "../components/Canvaslow";
import { Canvasbottomone } from "../components/Canvasbottomone";
import { Canvasbottomtwo } from "../components/Canvasbottomtwo";
import { Contactus } from "../components/Contactus";
import { Testpage } from "../components/Testpage";
import { News } from "../components/News";
import { Brands } from "../components/Brands";
import { Footer } from "../components/Footer";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      export default class SimpleSlider extends Component {
  render() {
    const settings = {
      dots: true,
      infinite: true,
      speed: 500,
      slidesToShow: 1,
      slidesToScroll: 1,
    };
    return (
      <div>
        <h2> Single Item</h2>
        <Slider {...settings}>
          <div>
            <h3>1</h3>
          </div>
          <div>
            <h3>2</h3>
          </div>
          <div>
            <h3>3</h3>
          </div>
          <div>
            <h3>4</h3>
          </div>
          <div>
            <h3>5</h3>
          </div>
          <div>
            <h3>6</h3>
          </div>
        </Slider>
      </div>
    );
  }
}
      <Header />
      <Canvas />
      <Canvasmid />
      <Canvaslow />
      <Canvasbottomone />
      <Canvasbottomtwo />

      <Contactus />
      <News />
      <Brands />
      <Footer />
      {/* <News /> */}
      {/*  */}
    </div>
  );
}
